/// Sockets emit events
const driverActivenessUpdate = 'driver-activeness-update';
const rideRequestDriverNotification = 'ride-request-driver-notification';
const rideInitiation = 'ride-initiation';
const rideCompletion = 'ride-completion';
const driverRideReject = 'driver-ride-reject';
const driverRideAcceptance = 'driver-ride-acceptance';
const driverLocationUpdate = 'driver-location-update';
const driverAtPickup = 'driver-at-pickup';
const driverAtDestination = 'driver-at-destination';
const rideCancellation = 'ride-cancellation';