/// Sockets emit events
const driverRideAcceptance = 'driver-ride-acceptance';
const driverRideReject = 'driver-ride-reject';
const driverRideDispatch = 'driver-ride-dispatch';
const driverLocationUpdate = 'driver-location-update';
const driverAtPickup = 'driver-at-pickup';
const driverActivenessUpdate = 'driver-activeness-update';
const rideRequestDriverNotification = 'ride-request-driver-notification';
const rideCancellation = 'ride-cancellation';
const rideInitiation = 'ride-initiation';
const rideCompletion = 'ride-completion';
const rideOnDispatch = 'ride-on-dispatch';
const rideOnTrip = 'ride-on-trip';